name: Релиз проекта

on:
  workflow_dispatch:
    inputs:
      version:
        description: Версия релиза
        required: true
        type: string

jobs:
  changelog:
    uses: Pacific-Agency/workflows/.github/workflows/changelog.yml@v0.4.0
    with:
      version: ${{ inputs.version }}
    secrets:
      BOT_ACCESS_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
